AWSTemplateFormatVersion: 2010-09-09
Description: 'AWS CloudFormation Stack for Lambda Function'

Parameters:
  EnvironmentType:
    Description: EnvironmentType
    Type: String
    AllowedValues:
      - 'production'
      - 'uat'
      - 'int'
      - 'qa2'
      - 'qa'
      - 'dev'
    Default: 'qa2'

Resources:
  S3UploadEventTriggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/secret/azkaban-*'
                - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/secret/azkaban/*'
                - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/secret/application-*'
                - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/secret/azkaban'
                - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:partner/crypto-*'
        - SNSPublishPolicy:
            TopicArn: !ImportValue bucket-upload-event-sns-Arn
      Tags:
        Service: mrburns
        Owner: Proton
        Department: Tech
        Stage: LMS

Outputs:
  S3UploadEventTriggerFunction:
    Description: "S3UploadEventTrigger Lambda Function ARN"
    Value: !GetAtt S3UploadEventTrigger.Arn
    Export:
      Name: bageeraS3UploadEventTrigger