AWSTemplateFormatVersion: '2010-09-09'
Description: 'EFS'

Resources:
  pqJobMetadataSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: !Join
                            - ''
                            - - !ImportValue pqJobMetadataFileSystem
                              - "-security-group"
        VpcId:
          Fn::ImportValue: Vpc
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 2049
            ToPort: 2049
            SourceSecurityGroupId: !ImportValue bageeraJobEcsSecurityGroupId

  pqJobMetadataMountTargetA:
    DependsOn: pqJobMetadataSecurityGroup
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: Fn::ImportValue pqJobMetadataFileSystem
      SubnetId: !Split [',',!ImportValue ServiceSubnet]
      SecurityGroups: 
        - !Ref pqJobMetadataSecurityGroup

  pqJobMetadataMountTargetB:
    DependsOn: pqJobMetadataSecurityGroup
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: Fn::ImportValue pqJobMetadataFileSystem
      SubnetId: !Split [',',!ImportValue ServiceSubnet]
      SecurityGroups: 
        - !Ref pqJobMetadataSecurityGroup

  pqJobMetadataMountTargetC:
    DependsOn: pqJobMetadataSecurityGroup
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: Fn::ImportValue pqJobMetadataFileSystem
      SubnetId: !Split [',',!ImportValue ServiceSubnet]
      SecurityGroups: 
        - !Ref pqJobMetadataSecurityGroup
