AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Variables
        Parameters:
          - AlertsSlackWebhookUrl
    ParameterLabels:
      AlertsSlackWebhookUrl:
        default: Alerts Slack Webhook Url

Parameters:
  AlertsSlackWebhookUrl:
    Type: String
    Description: Alerts Slack Webhook Url

Resources:
  AlertsSlackNotificationFunctionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonSNSFullAccess
      Environment:
        Variables:
          PQ_WHITELISTING_ALERTS_SLACK_WEBHOOK_URL: !Ref AlertsSlackWebhookUrl
      Tags:
        Service: bageera
        Owner: Proton
        Department: Tech
        Stage: LOS
  
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue pq-job-status-sns-Arn
      Protocol: lambda
      Endpoint: !GetAtt AlertsSlackNotificationFunctionFunction.Arn
  
  LambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt AlertsSlackNotificationFunctionFunction.Arn
      Principal: sns.amazonaws.com