AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AWS CloudFormation Stack for Lambda Function'

Parameters:
  EnvironmentType:
    Description: EnvironmentType
    Type: String
    AllowedValues:
      - 'production'
      - 'uat'
      - 'int'
      - 'qa2'
      - 'qa'
      - 'dev'
    Default: 'dev'
  BucketName:
    Description: Bucket Name
    Type: String

Resources:

  S3UploadEventTriggerFunction:
    Dependson: pqOfferBucket
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../s3UploadEventTriggerLambda/src
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSSMFullAccess
        - AmazonSNSFullAccess
        - AmazonS3FullAccess
        - AmazonEventBridgeFullAccess
                    
      Environment:
        Variables:
          SNS_TOPIC_ARN: !ImportValue pq-offer-bucket-upload-event-sns-Arn
          PQ_JOB_QUEUE_URL: !ImportValue pq-job-queue-Url
          ENV: !Ref EnvironmentType
          ALERT_SNS: !ImportValue pq-job-status-sns-Arn


      Tags:
        Service: bageera
        Owner: Proton
        Department: Tech
        Stage: LOS


  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule to Trigger Lambda on S3 upload
      EventBusName: default
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref BucketName
          object:
            key:
              - wildcard: offer/*/lpc/*/*/*.csv
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt S3UploadEventTriggerFunction.Arn
          Id: "S3UploadEventTriggerFunctionId"

  PermissionEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref S3UploadEventTriggerFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventBridgeRule.Arn


Outputs:
  S3UploadEventTriggerFunction:
    Description: "S3UploadEventTrigger Lambda Function ARN"
    Value: !GetAtt S3UploadEventTriggerFunction.Arn
    Export:
      Name: bageeraS3UploadEventTrigger